;;;;;;;;;;;;;;;;
;GAME VARIABLES;
;;;;;;;;;;;;;;;;
;ZP vars
;Temps: $00-$1F
GameMode		.equ $20
GameSubmode		.equ $21
SoundMutex		.equ $22
GlobalTimer		.equ $23
NMIMutex		.equ $24
BlackScreenTimer	.equ $25
VRAMBufferOffset	.equ $26
DemoFlag		.equ $27
SoundPRGBank		.equ $28
TitleCursorPos		.equ $29
PRNGValue		.equ $2A
TempCHRBanks		.equ $2B
EnemyPRGBank		.equ $32
TempLastBankSwitch	.equ $35
CHRBanks		.equ $37
OAMBufferOffset		.equ $3B
EnemyOAMStartIndex	.equ $3C
ScrollLockFlags		.equ $3D
ScrollLockOther		.equ $3E
JoypadDown		.equ $40
JoypadCur		.equ $42
MainGameSubmode		.equ $44
PausedFlag		.equ $45
PauseDisableFlag	.equ $46
DemoEndFlag		.equ $47
DemoTimer		.equ $48
DemoIndex		.equ $49
GameModeTimer		.equ $4A
CurLevel		.equ $4C
IRQContinueFlag		.equ $4D
SoundSubSaveBank	.equ $51
SoundSubSaveA		.equ $52
SoundSubSaveX		.equ $53
SoundSubSaveY		.equ $54
CurArea			.equ $55
LevelAreaNum		.equ $56
SelectCursorPos		.equ $57
TempIRQBufferHeight	.equ $58
IRQBufferHeight		.equ $5D
IRQBufferSub		.equ $62
TempIRQEnableFlag	.equ $67
IRQEnableFlag		.equ $68
IRQSubPointer		.equ $69
IRQNextHeight		.equ $6B
IRQLastFlag		.equ $6C
ElevatorYPos		.equ $6D
TempScrollLockFlags	.equ $6E
TempScrollLockOther	.equ $6F
LevelAreaHeight		.equ $71
LevelAreaWidth		.equ $72
CurScreenX		.equ $73
ScrollXPosLo		.equ $74
CurScreenY		.equ $75
ScrollYPosLo		.equ $76
ScrollEnemyXVel		.equ $77
ScrollEnemyYVel		.equ $78
ScrollXTilePos		.equ $79
ScrollYCollPosLo	.equ $7A
ScrollInitScreenCounter	.equ $7B
ScrollSeamXScreen	.equ $7C
ScrollSeamYScreen	.equ $7D
ScrollSeamXTile		.equ $7E
ScrollSeamYTile		.equ $7F
TempScrollSeamXTile	.equ $80
TempScrollSeamXScreen	.equ $81
ScrollVRAMPointer	.equ $82
ScrollYPrevFlag		.equ $84
ScrollSeamYTileLo	.equ $85
ScrollXDirection	.equ $86
ScrollYDirection	.equ $87
ScrollXFlag		.equ $88
ScrollYFlag		.equ $89
ScrollAttrVRAMPointer	.equ $8A
ScrollAttrBuffer	.equ $8C
ScrollAttrBufferOffs	.equ $95
CurEnemyIndex		.equ $96
ScrollDirectionFlags	.equ $97
SaveScrollX		.equ $98
SaveScrollY		.equ $99
HUDVRAMBase		.equ $9A
HUDRowIndex		.equ $9C
HUDPositionCur		.equ $9D
HUDPositionNext		.equ $9E
HUDPositionChangeFlag	.equ $9F
HUDVRAMPointer		.equ $A0
ScrollXCollPosHi	.equ $A2
ScrollYCollPosHi	.equ $A3
CatoblepasPlayerIndex	.equ $A4
ScrollPlayerYVel	.equ $A6
ScrollPlayerXVel	.equ $A7
ScrollXCollPosLo	.equ $A9
ScrollAxisFlags		.equ $AA
TempScrollSeamYTile	.equ $AE
TempScrollSeamYScreen	.equ $AF
CurPalette		.equ $B0
FadeInitFlag		.equ $B1
FadeTimer		.equ $B2
FadeDoneFlag		.equ $B3
FadeDirection		.equ $B4
LevelScrollFlags	.equ $B5
HUDCHRBank		.equ $B6
GameModeTimer2		.equ $B7
VictoryFlag		.equ $B8
PlayerXLo		.equ $B9
PlayerYLo		.equ $BB
PlayerXVelLo		.equ $BD
PlayerXVel		.equ $BF
PlayerYVelLo		.equ $C1
PlayerYVel		.equ $C3
PlayerPowLo		.equ $C5
PlayerPowHi		.equ $C7
WarpFlag		.equ $C9
BossPaletteFlashFlag	.equ $CC
RespawnGameOverTimer	.equ $CD
ScrollEnemyFlag		.equ $CE
ExplosionSoundLoopingID	.equ $CF
TempSoundDataPointer	.equ $E0
;Temps: $E2-$EE
SpriteBossModeFlag	.equ $F2
BossDeathSoundFlag	.equ $F3
TempJoypadDown		.equ $F8
TempJoypadCur		.equ $FA
TempMirror_PPUSCROLL_Y	.equ $FC
TempMirror_PPUSCROLL_X	.equ $FD
Mirror_PPUMASK		.equ $FE
TempMirror_PPUCTRL	.equ $FF

;ZP vars - Title context
TitleSubmode		.equ $70
TitleTimer		.equ $71
TitleCounter		.equ $72
PocketBulgeAnimOffs	.equ $77
PocketBulgeAnimTimer	.equ $7A
LogoScrollYVelLo	.equ $7D
LogoScrollYVelHi	.equ $7E
MonsterPeekAnimOffs	.equ $7F
MonstersOutYVelLo	.equ $80
MonstersOutYVelHi	.equ $84
MonstersOutXVelLo	.equ $88
MonstersOutXVelHi	.equ $8C
MonstersOutYLo		.equ $90
MonstersOutXLo		.equ $94
MonstersOutSpriteOffs	.equ $98
MonstersOutAnimOffs	.equ $9C

;ZP vars - Sound test context
SoundTestMusicIdx	.equ $70

;Sound vars
SoundTimer		.equ $0104
SoundID			.equ $010A
SoundBaseLength		.equ $0110
SoundControlFlags1	.equ $0116
SoundRepeatCounter	.equ $011C
SoundPointerLo		.equ $0122
SoundPointerHi		.equ $0128
SoundRepeatPtrLo	.equ $012E
SoundRepeatPtrHi	.equ $0134
SoundReturnPtrLo	.equ $013A
SoundReturnPtrHi	.equ $0140
SoundOutFreqHi		.equ $0146
SoundFreqLo		.equ $014C
SoundFreqHi		.equ $0152
SoundCurChannel		.equ $0155
SoundVol		.equ $0158
SoundOutIndex		.equ $015B
SoundOctave		.equ $015E
SoundPausedFlag		.equ $0163
SoundOutVol		.equ $0164
SoundDMCTimer		.equ $0166
SoundDuty		.equ $016A
SoundControlFlags2	.equ $0170
SoundFade		.equ $0176
SoundLoadID		.equ $0179
SoundPitch		.equ $017C
SoundInstrumentFlags	.equ $0182
SoundPitchShift		.equ $0185
SoundInst2Multiplier	.equ $0188
SoundInst2TimerStart	.equ $018B
SoundInst2Timer		.equ $018E
SoundInst1Timer		.equ $0191
SoundInst2Pitch		.equ $0194
SoundInst2Pointer	.equ $0197
SoundInst1Pointer	.equ $019A
SoundInst2		.equ $019D
SoundInst1		.equ $01A0
SoundInst2RepeatCounter	.equ $01A3
SoundInst1RepeatCounter	.equ $01A6
SoundInst2RepeatPointer	.equ $01A9
SoundInst1RepeatPointer	.equ $01AC
SoundFadeoutCounter	.equ $01AF
SoundFadeoutTimer	.equ $01B0
SoundFadeout		.equ $01B1
SoundTickFlag		.equ $01B2
SoundLoopingID		.equ $01B3
SoundSq1OutFreqLo	.equ $01B4
SoundInst2FreqLo	.equ $03C0
SoundInst2FreqHi	.equ $03C3
SoundEnvSMultiplier	.equ $03C6
SoundEnvSTimer		.equ $03C9
SoundEnvHDData		.equ $03CC
SoundEnvMode		.equ $03CE
SoundEnvHTimer		.equ $03D0
SoundEnvDTimer		.equ $03D2
SoundEnvSRData		.equ $03D4
SoundEnvRTimer		.equ $03D6
SoundEchoDuty		.equ $03D8
SoundEchoAmount		.equ $03DC
SoundEchoOffset		.equ $03DE
SoundEchoTimer		.equ $03E0
SoundOutDuty		.equ $03E2
SoundEchoVol		.equ $03E4
SoundEnvDMultiplier	.equ $03E6
SoundEnvRMultiplier	.equ $03E8
SoundEchoFlags		.equ $03EA
SoundTieTimer		.equ $03EC
SoundEchoBufferLo	.equ $03EE
SoundEchoBufferHi	.equ $03F6
SoundTempoTimer		.equ $03FE
SoundTempoReload	.equ $03FF

;WRAM vars
OAMBuffer		.equ $0200
VRAMBuffer		.equ $0300
HUDVRAMBuffer		.equ $0380
CollisionBuffer		.equ $0400

;Enemy vars
Enemy_Sprite		.equ $0500
Enemy_Y			.equ $0520
Enemy_YHi		.equ $0540
Enemy_X			.equ $0560
Enemy_XHi		.equ $0580
Enemy_Props		.equ $05A0
Enemy_Flags		.equ $05C0
Enemy_ID		.equ $05D2
Enemy_Mode		.equ $05E4
Enemy_XLo		.equ $05F6
Enemy_YLo		.equ $0608
Enemy_XVelLo		.equ $061A
Enemy_XVel		.equ $062C
Enemy_YVelLo		.equ $063E
Enemy_YVel		.equ $0650
Enemy_HP		.equ $0662
Enemy_Temp0		.equ $0674
Enemy_Temp1		.equ $0686
Enemy_AnimOffs		.equ $0698
Enemy_AnimTimer		.equ $06AA
Enemy_InvinTimer	.equ $06BC
Enemy_Temp2		.equ $06CE
Enemy_Temp3		.equ $06E0
Enemy_Temp4		.equ $06F2
Enemy_Temp5		.equ $0704

;Enemy vars - Intro/ending context
EndingGameplayTVMode	.equ $05EC
TVStaticDialogTimer	.equ $05FE
DialogVRAMBaseLo	.equ $05FF
TVStaticDialogCounter	.equ $0610
DialogVRAMBaseHi	.equ $0611
TVScrambleTimer		.equ $0622
EndingHUDPaletteOffs	.equ $0622
EndingDialogSetID	.equ $0622
DialogDataPointerLo	.equ $0623
TVScrambleStaticFlag	.equ $0634
DialogDataPointerHi	.equ $0635
IntroPlayerAnimOffs	.equ $0646
DialogTextTimer		.equ $0647
IntroPlayerAnimTimer	.equ $0658
DialogSetID		.equ $0659
TVBlinkTimer		.equ $066A
DialogDataIndex		.equ $066B
CreditsDialogID		.equ $066B
DialogID		.equ $067D
DialogTimer		.equ $068F
IntroEndingTimer2	.equ $068F
IntroEndingTimerLo	.equ $06A0
DialogUpdateMode	.equ $06A1
Level7BossFireFlag	.equ $06A1
CreditsUpdateMode	.equ $06A1
EndingLogoPaletteOffs	.equ $06A1
IntroEndingTimerHi	.equ $06B2
TempTVFaceWaveOffset	.equ $06B3
DialogVRAMPointerHi	.equ $06C5
DialogWriteMode		.equ $06D6
TVFaceWaveCounter	.equ $06D7
TVFaceWaveXBuffer	.equ $06E0
DialogVRAMPointerLo	.equ $070C
TVFaceWaveOffset	.equ $070D

;Player vars
PlayerHP		.equ $0716
PlayerMode		.equ $0718
PlayerHitFlags		.equ $071A
PlayerState		.equ $071C
PlayerAnimTimer		.equ $071E
PlayerAnimOffs		.equ $0720
PlayerRespawnStartFlag	.equ $0722
PlayerStateMode		.equ $0724
PlayerStateTimer	.equ $0726
PlayerJumpFallFlag	.equ $0728
PlayerJumpYPos		.equ $072A
PlayerCollTypeBottom	.equ $072C
PlayerScoreLo		.equ $072E
PlayerScoreMid		.equ $0730
PlayerFallTimer		.equ $0732
PlayerCharacter		.equ $0734
PlayerInvinTimer	.equ $0736
PlayerSprite		.equ $0738
PlayerRespawnX		.equ $073A
PlayerRespawnXHi	.equ $073C
PlayerRespawnY		.equ $073E
PlayerRespawnYHi	.equ $0740
PlayerLives		.equ $0742
PlayerJumpDownTimer	.equ $0744
PlayerAnimation		.equ $0746
PlayerKeyFlags		.equ $0748
PlayerFreezeTimer	.equ $074A
PlayerBonusMid		.equ $074C
PlayerCrossCollType	.equ $074E
PlayerPlatformIndex	.equ $0750
PlayerPlatformFlag	.equ $0752
PlayerAttackAnimOffs	.equ $0754
PlayerKeyPower		.equ $075A
PlayerAttackDuckFlag	.equ $075C
PlayerKeyXOffs		.equ $076A
PlayerAttackAnimTimer	.equ $076C
PlayerAttackXOffs	.equ $0774
PlayerAttackXOffsHi	.equ $077C
PlayerAttackYOffs	.equ $0784
PlayerLivesBonus	.equ $07A7

;Player vars - Select/stage clear context
SelectEyeTimer		.equ $071E
SelectEyeMode		.equ $0720
PlayerBonusLo		.equ $0728
PlayerBonusHi		.equ $072A
SelectEyeVRAMStrip	.equ $072C
SelectEyeOpen		.equ $0744

;WRAM vars
EndingHUDFlag		.equ $07A9
ItemCollectedBits	.equ $07AA
FreeMovementSpeed	.equ $07AC
ElevatorScrollX		.equ $07AD
ElevatorInitFlag	.equ $07AE
ElevatorVRAMDataPointer	.equ $07B1
ElevatorVRAMPointer	.equ $07B3
TempIRQBufferSub	.equ $07B7
AutoScrollDirFlags	.equ $07BC
AutoScrollXVel		.equ $07BD
AutoScrollYVel		.equ $07BE
SaveKeyEnemiesFlag	.equ $07BF
BGFloorScrollXLo	.equ $07C0
BGFloorScrollX		.equ $07C1
TVFaceWaveXLoBuffer	.equ $07C2
PaletteBuffer		.equ $07D0
SoftResetDataBuffer	.equ $07F0
CurMusic		.equ $07F4
NumContinues		.equ $07F5
TitleLevelSelectIndex	.equ $07F6
TitleLevelSelectFlag	.equ $07F7
UpdateHUDRowFlag	.equ $07F8
TopScoreLo		.equ $07FD
TopScoreMid		.equ $07FE
TopScoreHi		.equ $07FF

;;;;;;;;;;;;;;
;GAME DEFINES;
;;;;;;;;;;;;;;
ENEMY_EXPLOSION		.equ $01
ENEMY_EXPLOSION2	.equ $02
ENEMY_WITCHFIRE		.equ $03
ENEMY_ZOMBIE		.equ $04
ENEMY_WINGEDPANTHER	.equ $05
ENEMY_SKELETON		.equ $06
ENEMY_SKELETONFIRE	.equ $07
ENEMY_BEAST		.equ $08
ENEMY_HUNCHBACK		.equ $09
ENEMY_WITCHSPAWNER	.equ $0A
ENEMY_WITCH		.equ $0B
ENEMY_LEVEL1BOSS	.equ $0C
ENEMY_LEVEL1BOSSFIRE	.equ $0D
ENEMY_ROCFIRE		.equ $0E
ENEMY_GHOST		.equ $0F
ENEMY_GHOUL		.equ $10
ENEMY_GHOULFIRE		.equ $11
ENEMY_OGRE		.equ $12
ENEMY_GOBLIN		.equ $13
ENEMY_GOBLINFIRE	.equ $14
ENEMY_CERBERUS		.equ $15
ENEMY_LEVEL2BOSS	.equ $16
ENEMY_LEVEL2BOSSFIRE	.equ $17
ENEMY_ROC		.equ $18
ENEMY_HANIVER		.equ $19
ENEMY_HANIVERFIRE	.equ $1A
ENEMY_GOLFBALL		.equ $1B
ENEMY_CATOBLEPAS	.equ $1C
ENEMY_TRITON		.equ $1D
ENEMY_CHARONSPAWNER	.equ $1E
ENEMY_CHARONFALLING	.equ $1F
ENEMY_ITEMKEY		.equ $20
ENEMY_ITEMSCREW		.equ $21
;Unused
;
ENEMY_HYDRA		.equ $24
ENEMY_HYDRAFIRE		.equ $25
ENEMY_HOBGOBLIN		.equ $26
ENEMY_REDCAP		.equ $27
ENEMY_HARPYSPAWNER	.equ $28
ENEMY_HARPY		.equ $29
ENEMY_CHIMERA		.equ $2A
ENEMY_CHIMERAFIRE	.equ $2B
ENEMY_BABAYAGA		.equ $2C
ENEMY_WARP		.equ $2D
ENEMY_KALI		.equ $2E
ENEMY_KALIFIRE		.equ $2F
ENEMY_HARPYSPAWNER2	.equ $30
ENEMY_MANTICORE		.equ $31
ENEMY_BGCYCLOPS		.equ $32
ENEMY_COCKATRICE	.equ $33
ENEMY_BGFLOORSCROLL	.equ $34
ENEMY_KARNACK		.equ $35
ENEMY_STOVEFLAME	.equ $36
ENEMY_TENGU		.equ $37
ENEMY_COATLICUE		.equ $38
ENEMY_LEVEL4BOSS	.equ $39
ENEMY_LEVEL4BOSSFIRE	.equ $3A
ENEMY_LEVEL3BOSS	.equ $3B
ENEMY_LEVEL3BOSSPART	.equ $3C
ENEMY_LEVEL4ELEVATOR	.equ $3D
ENEMY_LEVEL3BOSSSPLASH	.equ $3E
ENEMY_BGWATERFALL	.equ $3F
ENEMY_BGWATERSCROLL	.equ $40
ENEMY_CHARON		.equ $41
ENEMY_LEVEL5BOSS	.equ $42
ENEMY_LEVEL5BOSSFIRE	.equ $43
ENEMY_LEVEL4BOSSCRANE	.equ $44
ENEMY_LEVEL3FALLSTART	.equ $45
ENEMY_MANTICOREFIRE	.equ $46
ENEMY_TENGUFIRE		.equ $47
ENEMY_COCKATRICEFIRE	.equ $48
ENEMY_TREX		.equ $49
ENEMY_TREXFIRE		.equ $4A
ENEMY_LEVEL6CRUSHER	.equ $4B
ENEMY_BEHEMOTH		.equ $4C
ENEMY_L6CRUSHERSPIKES	.equ $4D
ENEMY_WATERDROPSPAWNER	.equ $4E
ENEMY_WATERDROP		.equ $4F
ENEMY_LEVEL6ELEVATOR	.equ $50
ENEMY_MINOTAUR		.equ $51
ENEMY_GREATBEAST	.equ $52
ENEMY_GREATBEASTFIRE	.equ $53
ENEMY_LEVEL6ELEVATOR2	.equ $54
ENEMY_LEVEL6FALLSTART	.equ $55
ENEMY_LEVEL3BOSSFADE	.equ $56
ENEMY_LEVEL4BOSSFADE	.equ $57
ENEMY_LEVEL6BOSS	.equ $58
ENEMY_LEVEL6BOSSFIRE	.equ $59
ENEMY_LEVEL7BOSS	.equ $5A
ENEMY_LEVEL4FENCESCROLL	.equ $5B
ENEMY_LEVEL7BOSSFIRE	.equ $5C
ENEMY_WINDIGO		.equ $5D
ENEMY_ITEMHP		.equ $F0
;Unused
;
;
ENEMY_LEVEL3PLATFORM	.equ $F4
ENEMY_LEVEL4CRANE	.equ $F5

EF_ALLOWOFFSCREEN	.equ $20
EF_NOHITATTACK		.equ $40
EF_NOHITENEMY		.equ $80

SE_OPENHHAT		.equ $01
SE_CLOSEDHHAT		.equ $02
SE_SNARENOISE		.equ $03
SE_MIDCRASHNOISE	.equ $04
SE_HICRASHNOISE		.equ $05
SE_LOCRASHNOISE		.equ $06
SE_TYPING		.equ $07
SE_POCKETBULGE		.equ $08
SE_MONSTEROUT		.equ $0A
SE_CURSMOVE		.equ $0C
SE_SELECT		.equ $0D
SE_SLOPEPOWERRUN	.equ $0F
SE_TVSTATIC		.equ $11
SE_SCOREUP		.equ $12
SE_STAGECLEAR1UP	.equ $14
SE_LEVEL4CRANELOOP	.equ $16
SE_LEVEL4ELEVLOOP	.equ $18
SE_LEVEL4ELEVSLOWLOOP	.equ $19
SE_PLAYERJUMP		.equ $1A
SE_PLAYERDOUBLEJUMP	.equ $1B
SE_VAMPIREATTACK	.equ $1C
SE_MONSTERATTACK	.equ $1D
SE_BGWATERSCROLL	.equ $1E
SE_FALLSTART		.equ $1F
SE_FALLLAND		.equ $21
SE_LEVEL1BOSSFIRE	.equ $23
SE_ENEMYDEATHLOOP	.equ $25
SE_WITCHAPPEAR		.equ $27
SE_ROCFLY		.equ $28
SE_ROCDROP		.equ $29
SE_LEVEL2BOSSFIRE	.equ $2A
SE_PLAYERFREEZE		.equ $2B
SE_GOLFBALL		.equ $2D
SE_HANIVERFIRE		.equ $2F
SE_KALIFIRE		.equ $31
SE_LEVEL4BOSSFIRE	.equ $33
SE_CHIMERAFIRE		.equ $34
SE_COCKATRICEFIRE	.equ $35
SE_TREXFIRE		.equ $37
SE_GREATBEASTFIRE	.equ $38
SE_STOVEFLAME		.equ $3A
SE_BGCYCLOPS		.equ $3C
SE_HYDRAFIRE		.equ $3E
SE_SPLASH		.equ $3F
SE_ENEMYHIT		.equ $40
SE_BGWATERFALL		.equ $42
SE_WATERDROP		.equ $44
SE_ENEMYDEATH		.equ $45
SE_ITEMKEYLAND		.equ $47
SE_ITEMSCREWLAND	.equ $49
SE_LEVEL3BOSSAPPEAR	.equ $4B
SE_LEVEL3BOSSHIDE	.equ $4D
SE_LEVEL4CRANE		.equ $4F
SE_LOOPEND		.equ $51
SE_LEVEL4ELEV		.equ $53
SE_LEVEL4ELEVSLOW	.equ $54
SE_LEVEL4ELEVSTOP	.equ $55
SE_LEVEL5BOSSFIRE	.equ $57
SE_PLAYERFREEZE2	.equ $59
SE_LEVEL6CRUSHER	.equ $5B
SE_LEVEL6CRUSHERMOVE	.equ $5D
SE_ITEMHP		.equ $5F
SE_TVSTATIC2		.equ $60
SE_BOSSHIT		.equ $63
SE_LEVEL6BOSSFIRE	.equ $65
SE_LEVEL7BOSSFIRE	.equ $67
SE_LEVEL7BOSSEYEFLASH	.equ $68
SE_LEVEL6BOSSDEATH	.equ $6A
SE_TVSTATIC3		.equ $6D
SE_1UP			.equ $70
SE_PLAYERDEATH		.equ $71
SE_PAUSE		.equ $72
DMC_HITOM		.equ $73
DMC_MIDTOM		.equ $74
DMC_LOTOM		.equ $75
DMC_SNARE		.equ $76
DMC_BASS		.equ $77
DMC_VAMPIREHURT		.equ $78
DMC_MONSTERHURT		.equ $79
DMC_BOSSDEATH0		.equ $7A
DMC_BOSSDEATH1		.equ $7B
DMC_BOSSDEATH2		.equ $7C
MUSIC_LEVEL1		.equ $7D
MUSIC_LEVEL2		.equ $81
MUSIC_LEVEL3		.equ $85
MUSIC_LEVEL4		.equ $89
MUSIC_LEVEL5		.equ $8D
MUSIC_LEVEL6		.equ $91
MUSIC_BOSS		.equ $95
MUSIC_BOSSRUSH		.equ $99
MUSIC_BOSSRUSHINT	.equ $9D
MUSIC_SCENE0		.equ $A1
MUSIC_TITLE		.equ $A5
MUSIC_SELECT		.equ $A9
MUSIC_SCENE1		.equ $AD
MUSIC_BOSS2		.equ $B0
MUSIC_CREDITS		.equ $B4
MUSIC_CLEAR		.equ $B8
MUSIC_GAMEOVER		.equ $BC

SF1_SNDEFF		.equ $01
SF1_REST		.equ $40
SF1_SWEEP		.equ $80
SF2_LOOP		.equ $01
SF2_INSUB		.equ $10
SF2_REPEAT		.equ $80
SFI_INST1		.equ $01
SFI_INST2		.equ $10
SFE_ENABLE		.equ $01
SFE_UPDATE		.equ $02
SFE_OUTPUT		.equ $08
